// src/views/Settings.vue
<template>
  <div class="settings-page">
    <el-card class="settings-card">
      <template #header>
        <div class="card-header">
          <el-icon><Upload /></el-icon>
          <span>数据导入导出</span>
        </div>
      </template>
      <div class="action-buttons">
        <el-button type="primary" @click="handleExport" :loading="exporting">
          <el-icon><Download /></el-icon>
          导出数据
        </el-button>
        <el-button type="warning" @click="handleImport" :loading="importing">
          <el-icon><Upload /></el-icon>
          导入数据
        </el-button>
      </div>
      <div class="action-desc">
        <p>导出：将当前所有数据导出为 Excel 文件</p>
        <p>导入：从 Excel 文件导入数据（将替换当前数据，原数据会自动备份）</p>
      </div>
    </el-card>

    <el-card class="settings-card">
      <template #header>
        <div class="card-header">
          <el-icon><Folder /></el-icon>
          <span>数据文件配置</span>
        </div>
      </template>
      <div class="path-config">
        <div class="current-path">
          <span class="label">当前数据文件：</span>
          <el-tag type="info" class="path-tag">{{ dataPath || '加载中...' }}</el-tag>
        </div>
        <div class="path-actions">
          <el-button type="primary" @click="handleSelectPath">
            <el-icon><FolderOpened /></el-icon>
            选择文件
          </el-button>
        </div>
      </div>
      <div class="action-desc">
        <p>选择一个 .xlsx 文件作为数据存储位置</p>
        <p>修改后需要重启应用才能生效</p>
      </div>
    </el-card>

    <el-card class="settings-card">
      <template #header>
        <div class="card-header">
          <el-icon><Warning /></el-icon>
          <span>安全设置</span>
        </div>
      </template>
      <el-form label-width="120px">
        <el-form-item label="允许删除">
          <el-switch v-model="allowDeleteVal" @change="handleAllowDeleteChange" />
          <span class="form-tip">开启后各管理页面的删除按钮才可见</span>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="settings-card">
      <template #header>
        <div class="card-header">
          <el-icon><Clock /></el-icon>
          <span>自动备份配置</span>
        </div>
      </template>
      <div class="backup-config">
        <el-form label-width="120px">
          <el-form-item label="保留份数">
            <el-input-number v-model="backupCount" :min="1" :max="100" @change="saveBackupConfig" />
            <span class="form-tip">超过此数量将自动删除最早的备份</span>
          </el-form-item>
          <el-form-item label="备份目录">
            <div class="backup-path-row">
              <el-tag type="info" class="path-tag">{{ backupConfig.effectiveBackupDir || '加载中...' }}</el-tag>
              <el-button size="small" @click="handleSelectBackupDir">更改</el-button>
              <el-button size="small" type="info" @click="resetBackupDir">恢复默认</el-button>
            </div>
          </el-form-item>
          <el-form-item label="备份策略">
            <el-tag type="success">启动时自动备份</el-tag>
            <el-tag type="success" style="margin-left: 8px">退出时自动备份</el-tag>
          </el-form-item>
        </el-form>
      </div>
      <div class="action-buttons" style="margin-top: 16px">
        <el-button type="primary" @click="handleBackupNow" :loading="backingUp">
          <el-icon><CopyDocument /></el-icon>
          立即备份
        </el-button>
      </div>
    </el-card>

    <el-card class="settings-card">
      <template #header>
        <div class="card-header">
          <el-icon><Document /></el-icon>
          <span>备份记录</span>
          <el-button size="small" style="margin-left: auto" @click="loadBackups">刷新</el-button>
        </div>
      </template>
      <el-table :data="backups" style="width: 100%" max-height="400">
        <el-table-column prop="backup_time" label="备份时间" width="180" />
        <el-table-column prop="backup_reason" label="备份原因" width="120" />
        <el-table-column prop="backup_md5" label="MD5" min-width="200" show-overflow-tooltip />
        <el-table-column label="锁定" width="80" align="center">
          <template #default="{ row, $index }">
            <el-button size="small" :type="row.locked ? 'warning' : 'info'" link @click="handleToggleLock($index)">
              <el-icon><Lock v-if="row.locked" /><Unlock v-else /></el-icon>
            </el-button>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="120" fixed="right">
          <template #default="{ row }">
            <el-button size="small" type="warning" @click="handleRestore(row)">恢复</el-button>
          </template>
        </el-table-column>
      </el-table>
      <div v-if="backups.length === 0" style="text-align: center; color: #909399; padding: 20px">
        暂无备份记录
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { save, open } from '@tauri-apps/plugin-dialog'
import { readFile, writeFile } from '@tauri-apps/plugin-fs'
import { dataApi, settingsApi, backupApi, allowDeleteApi } from '../api'

const exporting = ref(false)
const importing = ref(false)
const backingUp = ref(false)
const dataPath = ref('')
const backupCount = ref(10)
const backupConfig = ref<any>({})
const backups = ref<any[]>([])
const allowDeleteVal = ref(false)

async function handleAllowDeleteChange(val: boolean) {
  await allowDeleteApi.set(val)
  ElMessage.success(val ? '已开启删除功能' : '已关闭删除功能')
}

onMounted(async () => {
  try {
    const result = await settingsApi.getDataPath()
    dataPath.value = result as string
  } catch (error: any) {
    console.error('获取数据路径失败:', error)
  }
  await loadBackupConfig()
  await loadBackups()
  try { allowDeleteVal.value = await allowDeleteApi.get() } catch {}
})

async function loadBackupConfig() {
  try {
    const config = await backupApi.getConfig()
    backupConfig.value = config
    backupCount.value = config.backupCount || 10
  } catch (error: any) {
    console.error('获取备份配置失败:', error)
  }
}

async function loadBackups() {
  try {
    const result = await backupApi.list()
    backups.value = Array.isArray(result) ? result : []
  } catch (error: any) {
    console.error('获取备份列表失败:', error)
  }
}

async function handleToggleLock(index: number) {
  try {
    const result = await backupApi.toggleLock(index)
    if (result.success) {
      backups.value[index].locked = result.locked
      ElMessage.success(result.locked ? '已锁定' : '已解锁')
    }
  } catch (error: any) {
    ElMessage.error('操作失败: ' + (error.message || error))
  }
}

async function saveBackupConfig() {
  try {
    await backupApi.setConfig(backupCount.value, backupConfig.value.backupPath || null)
    ElMessage.success('备份配置已保存')
  } catch (error: any) {
    ElMessage.error('保存失败: ' + (error.message || error))
  }
}

async function handleBackupNow() {
  try {
    await ElMessageBox.confirm(
      '确定要立即备份当前数据吗？',
      '确认备份',
      { type: 'info', confirmButtonText: '确定备份', cancelButtonText: '取消' }
    )
  } catch {
    return
  }
  backingUp.value = true
  try {
    const result = await backupApi.backup()
    if (result.skipped) {
      ElMessage.info(result.message || '文件内容未变化，跳过备份')
    } else {
      ElMessage.success('备份成功')
    }
    await loadBackups()
  } catch (error: any) {
    ElMessage.error('备份失败: ' + (error.message || error))
  } finally {
    backingUp.value = false
  }
}

async function handleRestore(backup: any) {
  try {
    await ElMessageBox.confirm(
      `确定要恢复此备份吗？\n${backup.file_path}\n\n当前数据将自动备份。`,
      '确认恢复',
      { type: 'warning', confirmButtonText: '确定恢复', cancelButtonText: '取消' }
    )
    await backupApi.restore(backup.file_path)
    ElMessage.success('恢复成功，请重启应用')
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('恢复失败: ' + (error.message || error))
    }
  }
}

async function handleSelectBackupDir() {
  try {
    const selected = await open({
      directory: true,
      multiple: false,
      title: '选择备份目录'
    })
    if (!selected) return
    backupConfig.value.backupPath = selected as string
    backupConfig.value.effectiveBackupDir = selected as string
    await backupApi.setConfig(backupCount.value, selected as string)
    ElMessage.success('备份目录已更新')
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('设置失败: ' + (error.message || error))
    }
  }
}

async function resetBackupDir() {
  backupConfig.value.backupPath = null
  backupConfig.value.effectiveBackupDir = backupConfig.value.defaultBackupDir
  await backupApi.setConfig(backupCount.value, null)
  ElMessage.success('已恢复默认备份目录')
}

async function handleExport() {
  exporting.value = true
  try {
    const result = await dataApi.exportData()
    const bytes = Uint8Array.from(atob(result.data), c => c.charCodeAt(0))

    const filePath = await save({
      defaultPath: result.filename,
      filters: [{ name: 'Excel 文件', extensions: ['xlsx'] }]
    })
    if (!filePath) return

    await writeFile(filePath, bytes)
    ElMessage.success('导出成功')
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('导出失败: ' + (error.message || error))
    }
  } finally {
    exporting.value = false
  }
}

async function handleImport() {
  importing.value = true
  try {
    const filePath = await open({
      filters: [{ name: 'Excel 文件', extensions: ['xlsx'] }],
      multiple: false
    })
    if (!filePath) return

    await ElMessageBox.confirm(
      '导入将替换当前所有数据（原数据会自动备份），确定继续？',
      '确认导入',
      { type: 'warning', confirmButtonText: '确定导入', cancelButtonText: '取消' }
    )

    const fileBuffer = await fetchFileAsBase64(filePath as string)
    const result = await dataApi.importData(fileBuffer)

    const statsText = Object.entries(result.stats)
      .map(([name, count]) => `${name}: ${count} 条`)
      .join('\n')

    await ElMessageBox.alert(
      `导入成功！\n\n${statsText}`,
      '导入结果',
      { type: 'success' }
    )

    window.location.reload()
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('导入失败: ' + (error.message || error))
    }
  } finally {
    importing.value = false
  }
}

async function fetchFileAsBase64(filePath: string): Promise<string> {
  const bytes = await readFile(filePath)
  let binary = ''
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i])
  }
  return btoa(binary)
}

async function handleSelectPath() {
  try {
    const selected = await open({
      filters: [{ name: 'Excel 文件', extensions: ['xlsx'] }],
      multiple: false,
      title: '选择数据文件'
    })
    if (!selected) return

    const newPath = selected as string
    await ElMessageBox.confirm(
      `确定将数据文件切换到：\n${newPath}\n\n修改后需要重启应用才能生效。`,
      '确认修改',
      { type: 'warning', confirmButtonText: '确定', cancelButtonText: '取消' }
    )

    const result = await settingsApi.setDataPath(newPath)
    if (result.success) {
      dataPath.value = result.filePath
      ElMessage.success('数据文件已更新，请重启应用')
    }
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('设置失败: ' + (error.message || error))
    }
  }
}
</script>

<style scoped>
.settings-page {
  max-width: 800px;
  margin: 0 auto;
}

.settings-card {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 16px;
  font-weight: 600;
}

.action-buttons {
  display: flex;
  gap: 16px;
  margin-bottom: 16px;
}

.action-desc {
  color: #909399;
  font-size: 13px;
  line-height: 1.8;
}

.action-desc p {
  margin: 0;
}

.path-config {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
}

.current-path {
  display: flex;
  align-items: center;
  gap: 8px;
}

.label {
  color: #606266;
  font-size: 14px;
}

.path-tag {
  font-family: monospace;
  font-size: 13px;
  max-width: 400px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.path-actions {
  flex-shrink: 0;
}

.backup-config {
  margin-bottom: 0;
}

.form-tip {
  color: #909399;
  font-size: 12px;
  margin-left: 12px;
}

.backup-path-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>

// src/pages/settings.tsx
import { useState, useEffect, useCallback } from 'react'
import {
  Download,
  Upload,
  FolderOpen,
  RotateCcw,
  Shield,
  Save,
  Undo2,
  Lock,
  Unlock,
  RefreshCw,
  FileDown,
  Folder,
} from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { InputNumber } from '@/components/ui/input-number'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { useAllowDelete } from '@/hooks/use-allow-delete'
import { dataApi, settingsApi, backupApi } from '@/api'
import { save, open } from '@tauri-apps/plugin-dialog'
import { readFile, writeFile } from '@tauri-apps/plugin-fs'
import { toast } from 'sonner'

function base64ToUint8Array(base64: string): Uint8Array {
  const binary = atob(base64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i)
  }
  return bytes
}

export default function SettingsPage() {
  const { allowDelete, set: setAllowDelete } = useAllowDelete()

  // Data path
  const [dataPath, setDataPath] = useState('')
  const [dataPathLoading, setDataPathLoading] = useState(false)

  // Backup config
  const [backupCount, setBackupCount] = useState<number | undefined>(3)
  const [backupDir, setBackupDir] = useState('')
  const [backupConfigLoading, setBackupConfigLoading] = useState(false)

  // Backup list
  const [backupList, setBackupList] = useState<any[]>([])
  const [backupListLoading, setBackupListLoading] = useState(false)

  // Confirm dialogs
  const [importConfirmOpen, setImportConfirmOpen] = useState(false)
  const [pendingImportData, setPendingImportData] = useState<string>('')
  const [pendingImportFilename, setPendingImportFilename] = useState('')
  const [restoreConfirmOpen, setRestoreConfirmOpen] = useState(false)
  const [pendingRestorePath, setPendingRestorePath] = useState('')

  // Loading states
  const [exporting, setExporting] = useState(false)
  const [importing, setImporting] = useState(false)
  const [backingUp, setBackingUp] = useState(false)

  // Load data path
  const loadDataPath = useCallback(async () => {
    setDataPathLoading(true)
    try {
      const path = await settingsApi.getDataPath()
      setDataPath(path || '')
    } catch (error) {
      console.error('Failed to load data path:', error)
    } finally {
      setDataPathLoading(false)
    }
  }, [])

  // Load backup config
  const loadBackupConfig = useCallback(async () => {
    setBackupConfigLoading(true)
    try {
      const config = await backupApi.getConfig()
      if (config) {
        setBackupCount(config.backupCount ?? 3)
        setBackupDir(config.backupPath || '')
      }
    } catch (error) {
      console.error('Failed to load backup config:', error)
    } finally {
      setBackupConfigLoading(false)
    }
  }, [])

  // Load backup list
  const loadBackupList = useCallback(async () => {
    setBackupListLoading(true)
    try {
      const list = await backupApi.list()
      setBackupList(Array.isArray(list) ? list : [])
    } catch (error) {
      console.error('Failed to load backup list:', error)
    } finally {
      setBackupListLoading(false)
    }
  }, [])

  useEffect(() => {
    loadDataPath()
    loadBackupConfig()
    loadBackupList()
  }, [loadDataPath, loadBackupConfig, loadBackupList])

  // Handle export
  const handleExport = async () => {
    setExporting(true)
    try {
      const result = await dataApi.exportData()
      if (result && result.filename && result.data) {
        const filePath = await save({
          defaultPath: result.filename,
          filters: [{ name: 'Excel', extensions: ['xlsx'] }],
        })
        if (filePath) {
          const bytes = base64ToUint8Array(result.data)
          await writeFile(filePath, bytes)
          toast.success('导出成功')
        }
      }
    } catch (error) {
      console.error('Export failed:', error)
      toast.error('导出失败')
    } finally {
      setExporting(false)
    }
  }

  // Handle import file selection
  const handleImport = async () => {
    try {
      const selected = await open({
        multiple: false,
        filters: [{ name: 'Excel', extensions: ['xlsx'] }],
      })
      if (!selected) return

      const filePath = typeof selected === 'string' ? selected : selected
      const content = await readFile(filePath)
      const base64 = btoa(String.fromCharCode(...content))
      const filename = typeof filePath === 'string' ? filePath.split(/[/\\]/).pop() || 'data.xlsx' : 'data.xlsx'

      setPendingImportData(base64)
      setPendingImportFilename(filename)
      setImportConfirmOpen(true)
    } catch (error) {
      console.error('Import failed:', error)
      toast.error('导入失败')
    }
  }

  // Confirm import
  const confirmImport = async () => {
    setImporting(true)
    try {
      await dataApi.importData(pendingImportData)
      toast.success('导入成功，页面即将刷新')
      setImportConfirmOpen(false)
      setPendingImportData('')
      setPendingImportFilename('')
      setTimeout(() => window.location.reload(), 1000)
    } catch (error) {
      console.error('Import failed:', error)
      toast.error('导入失败')
    } finally {
      setImporting(false)
    }
  }

  // Handle select new data path
  const handleSelectDataPath = async () => {
    try {
      const selected = await open({
        multiple: false,
        filters: [{ name: 'Excel', extensions: ['xlsx'] }],
      })
      if (!selected) return

      const filePath = typeof selected === 'string' ? selected : selected
      await settingsApi.setDataPath(filePath)
      setDataPath(filePath)
      toast.success('数据文件路径已更新')
    } catch (error) {
      console.error('Failed to set data path:', error)
      toast.error('设置数据文件路径失败')
    }
  }

  // Handle toggle allow delete
  const handleToggleDelete = async (checked: boolean) => {
    try {
      await setAllowDelete(checked)
      toast.success(checked ? '已开启删除权限' : '已关闭删除权限')
    } catch (error) {
      console.error('Failed to toggle delete:', error)
      toast.error('切换删除权限失败')
    }
  }

  // Handle save backup config
  const handleSaveBackupConfig = async () => {
    if (backupCount === undefined || backupCount < 1) {
      toast.error('请输入有效的备份数量')
      return
    }
    try {
      await backupApi.setConfig(backupCount, backupDir || null)
      toast.success('备份配置已保存')
    } catch (error) {
      console.error('Failed to save backup config:', error)
      toast.error('保存备份配置失败')
    }
  }

  // Handle select backup directory
  const handleSelectBackupDir = async () => {
    try {
      const selected = await open({
        directory: true,
        multiple: false,
      })
      if (!selected) return

      const dirPath = typeof selected === 'string' ? selected : selected
      setBackupDir(dirPath)
    } catch (error) {
      console.error('Failed to select backup dir:', error)
      toast.error('选择备份目录失败')
    }
  }

  // Handle reset backup directory
  const handleResetBackupDir = () => {
    setBackupDir('')
  }

  // Handle manual backup
  const handleBackup = async () => {
    setBackingUp(true)
    try {
      await backupApi.backup()
      toast.success('手动备份成功')
      await loadBackupList()
    } catch (error) {
      console.error('Backup failed:', error)
      toast.error('手动备份失败')
    } finally {
      setBackingUp(false)
    }
  }

  // Handle toggle lock
  const handleToggleLock = async (index: number) => {
    try {
      await backupApi.toggleLock(index)
      toast.success('锁定状态已切换')
      await loadBackupList()
    } catch (error) {
      console.error('Failed to toggle lock:', error)
      toast.error('切换锁定状态失败')
    }
  }

  // Handle restore
  const handleRestore = async (backupPath: string) => {
    setPendingRestorePath(backupPath)
    setRestoreConfirmOpen(true)
  }

  // Confirm restore
  const confirmRestore = async () => {
    try {
      await backupApi.restore(pendingRestorePath)
      toast.success('备份恢复成功，页面即将刷新')
      setRestoreConfirmOpen(false)
      setPendingRestorePath('')
      setTimeout(() => window.location.reload(), 1000)
    } catch (error) {
      console.error('Restore failed:', error)
      toast.error('备份恢复失败')
    }
  }

  return (
    <div className="flex flex-col gap-6 p-6 max-w-4xl mx-auto">
      {/* Section 1: Data Import/Export */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileDown className="h-5 w-5" />
            数据导入导出
          </CardTitle>
          <CardDescription>
            导出当前数据为 Excel 文件，或从 Excel 文件导入数据
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <Button
              variant="outline"
              onClick={handleExport}
              disabled={exporting}
            >
              <Download className="h-4 w-4 mr-2" />
              {exporting ? '导出中...' : '导出数据'}
            </Button>
            <Button
              variant="outline"
              onClick={handleImport}
              disabled={importing}
            >
              <Upload className="h-4 w-4 mr-2" />
              {importing ? '导入中...' : '导入数据'}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Section 2: Data File Configuration */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Folder className="h-5 w-5" />
            数据文件配置
          </CardTitle>
          <CardDescription>
            当前数据文件的存储路径
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-4">
            <div className="flex-1">
              <Label>当前路径</Label>
              <div className="mt-1 p-2 rounded-md bg-muted text-sm font-mono break-all">
                {dataPathLoading ? '加载中...' : (dataPath || '未配置')}
              </div>
            </div>
            <Button
              variant="outline"
              onClick={handleSelectDataPath}
              disabled={dataPathLoading}
            >
              <FolderOpen className="h-4 w-4 mr-2" />
              选择文件
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Section 3: Security Settings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            安全设置
          </CardTitle>
          <CardDescription>
            控制是否允许删除操作
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between">
            <div>
              <Label>允许删除</Label>
              <p className="text-sm text-muted-foreground">
                开启后允许在各模块中删除数据记录
              </p>
            </div>
            <Switch
              checked={allowDelete}
              onCheckedChange={handleToggleDelete}
            />
          </div>
        </CardContent>
      </Card>

      {/* Section 4: Auto Backup Configuration */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Save className="h-5 w-5" />
            自动备份配置
          </CardTitle>
          <CardDescription>
            配置自动备份的数量和存储目录
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="w-48">
              <Label>备份数量</Label>
              <InputNumber
                value={backupCount}
                onChange={setBackupCount}
                min={1}
                max={99}
                className="mt-1"
                disabled={backupConfigLoading}
              />
            </div>
            <div className="flex-1">
              <Label>备份目录</Label>
              <div className="mt-1 flex items-center gap-2">
                <div className="flex-1 p-2 rounded-md bg-muted text-sm font-mono break-all">
                  {backupDir || '使用默认目录'}
                </div>
                <Button variant="outline" size="sm" onClick={handleSelectBackupDir}>
                  <FolderOpen className="h-4 w-4 mr-1" />
                  更改
                </Button>
                <Button variant="outline" size="sm" onClick={handleResetBackupDir}>
                  <RotateCcw className="h-4 w-4 mr-1" />
                  重置
                </Button>
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <Button onClick={handleSaveBackupConfig} disabled={backupConfigLoading}>
              保存配置
            </Button>
            <Button
              variant="outline"
              onClick={handleBackup}
              disabled={backingUp}
            >
              <RefreshCw className="h-4 w-4 mr-2" />
              {backingUp ? '备份中...' : '手动备份'}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Section 5: Backup Records */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Undo2 className="h-5 w-5" />
            备份记录
          </CardTitle>
          <CardDescription>
            查看所有备份记录，可锁定或恢复指定备份
          </CardDescription>
        </CardHeader>
        <CardContent>
          {backupListLoading ? (
            <div className="py-8 text-center text-muted-foreground">加载中...</div>
          ) : backupList.length === 0 ? (
            <div className="py-8 text-center text-muted-foreground">暂无备份记录</div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>备份时间</TableHead>
                  <TableHead>备份原因</TableHead>
                  <TableHead>MD5</TableHead>
                  <TableHead className="w-20">锁定</TableHead>
                  <TableHead className="w-20">恢复</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {backupList.map((backup, index) => (
                  <TableRow key={index}>
                    <TableCell className="font-mono text-sm">
                      {backup.backup_time || '-'}
                    </TableCell>
                    <TableCell>{backup.backup_reason || '-'}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">
                      {backup.backup_md5 ? backup.backup_md5.substring(0, 16) + '...' : '-'}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleToggleLock(index)}
                        title={backup.locked ? '解锁' : '锁定'}
                      >
                        {backup.locked ? (
                          <Lock className="h-4 w-4 text-primary" />
                        ) : (
                          <Unlock className="h-4 w-4 text-muted-foreground" />
                        )}
                      </Button>
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleRestore(backup.backup_path || '')}
                        title="恢复此备份"
                      >
                        <RotateCcw className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Import Confirm Dialog */}
      <AlertDialog open={importConfirmOpen} onOpenChange={setImportConfirmOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>确认导入</AlertDialogTitle>
            <AlertDialogDescription>
              确定要导入文件 "{pendingImportFilename}" 吗？导入操作将替换当前所有数据，此操作不可撤销。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={importing}>取消</AlertDialogCancel>
            <AlertDialogAction onClick={confirmImport} disabled={importing}>
              {importing ? '导入中...' : '确认导入'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Restore Confirm Dialog */}
      <AlertDialog open={restoreConfirmOpen} onOpenChange={setRestoreConfirmOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>确认恢复</AlertDialogTitle>
            <AlertDialogDescription>
              确定要恢复此备份吗？恢复操作将替换当前所有数据，此操作不可撤销。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction onClick={confirmRestore}>
              确认恢复
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
